name: test-get-istioctl

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-istio:
    runs-on: ubuntu-latest
    steps:
      - name: get istioctl
        id: get-istioctl
        uses: istio/get-istioctl@main
        with:
          version: '1.11.*'
      - name: Run Test
        run: |
          if [ $(istioctl version --remote=false) == "1.11.8" ]; then
             echo "Test Passed"
          else
             echo "Test Failed"
             exit 1
          fi
